house-track:
  scheduled:
    enabled: true
  yad2:
    cities:
      haifa: 4000
      kiryat-mozkin: 8200
    neighborhoods:
      savyoni-hacarmel: 634
      ramat-alon: 635
      ramat-chen: 640
      neot-peres: 607
      mishkenot-omanim: 458
      vardia: 627
      ahuza: 613
      almogi: 636
      begin: 615
      golda: 631

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}